### ISSUE TITLE
webserver auth broke when upgrading from v7.7 -> v7.8

### ISSUE THREAD

**Issue by codertee** [pgadmin-org/pgadmin4#6907]
After upgrading pgadmin4 from 7.7 to 7.8 webserver auth stopped working.

**To Reproduce**

1. Install `pgadmin4-server` from `deb https://ftp.postgresql.org/pub/pgadmin/pgadmin4/apt/focal pgadmin4 main`
2. Configure `/etc/pgadmin/config_system.py`
```python
AUTHENTICATION_SOURCES = ["webserver", "internal"]
WEBSERVER_AUTO_CREATE_USER = True
WEBSERVER_REMOTE_USER = "My-User-Header"
```
3. Have a webserver set `My-User-Header` HTTP header
4. Use a browser to log in through the webserver to pgadmin4 app

**Expected behavior**

When authenticating with webserver, pgadmin webapp should appear.

**Error message**

`/var/log/pgadmin4.log`:
```
2023-10-30 19:18:17,870: ERROR  pgadmin:        'NoneType' object has no attribute 'replace'
Traceback (most recent call last):
  File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/pgadmin4/venv/lib/python3.8/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/usr/pgadmin4/web/pgadmin/tools/user_management/__init__.py", line 106, in current_user_info
    email=current_user.email.replace("'","\\'"),
AttributeError: 'NoneType' object has no attribute 'replace'
```

**Additional context**

Could it be that previously auto-generated users did not get e-mail addresses and now the v7.8 update assumes every users must have e-mail address?

**Comment by yogeshmahajan-1903** [comment]
Duplicate of #6874 . Issue will be fixed in 7.9. WA for this is adding email in web server user profile.
