### ISSUE TITLE
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security'  (RM #7647)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#5285]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/7647***
*Originally created by **Bastiaan Wakkie** at 2022-08-27 10:34:52 UTC.*

After upgrade to 6.13 in an virtual environment with python 3.10 and restarting I am getting the following error which results in pgadmin4 not starting:

<pre>
/python310/lib/python3.10/site-packages/pgadmin4/pgadmin/__init__.py", line 28, in <module>
    from flask_login import user_logged_in, user_logged_out
  File "/data/venv/pgadmin/python310/lib/python3.10/site-packages/flask_login/__init__.py", line 16, in <module>
    from .login_manager import LoginManager
  File "/data/venv/pgadmin/python310/lib/python3.10/site-packages/flask_login/login_manager.py", line 24, in <module>
    from .utils import (login_url as make_login_url, _create_identifier,
  File "/data/venv/pgadmin/python310/lib/python3.10/site-packages/flask_login/utils.py", line 13, in <module>
    from werkzeug.security import safe_str_cmp
ImportError: cannot import name 'safe_str_cmp' from 'werkzeug.security' (/data/venv/pgadmin/python310/lib/python3.10/site-packages/werkzeug/security.py)
</pre>

Downgrading to Werkzeug 2.0.0 solved it for me.

Solution found here:
https://stackoverflow.com/questions/71652965/importerror-cannot-import-name-safe-str-cmp-from-werkzeug-security
pip install Werkzeug==2.0.0

**Comment by yogeshmahajan-1903** [comment]
Flask_login is upgrade to 0.6.2. Hence closing the issue.
