### ISSUE TITLE
AttributeError: 'Request' object has no attribute 'is_xhr' (RM #5174)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3306]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5174***
*Originally created by **Kris Avi** at 2020-02-10 14:36:00 UTC.*

https://stackoverflow.com/questions/60131900/weird-is-xhr-error-when-deploying-flask-app-to-heroku

Error is the same and cause is the same as well. The path to the error can differ a bit.

requirements.txt should be updated to reflect it is not working with 015.0 and greater but more like version that is lower than 1.0.0 for the time being.

**Comment by dpage** [comment]
Issue closed on Redmine.
