### ISSUE TITLE
macOS 15.6.1 (24G90) - pgAdmin v9.7 Not able to connect to any SSL Tunnel database as previously registered

### ISSUE THREAD

**Issue by EddySoeparmin235** [pgadmin-org/pgadmin4#9103]
I've been using pgAdmin for almost 2 years in macOS. This morning  when I upgraded to v9.7, I'm not able to connect to any of my previously registered server. In v9.6, it only prompts for the SSL Tunnel password, and if I entered it incorrectly then it'll prompt both SSL and db password. I entered both password correctly, and I got the error message:

module 'paramiko' has no attribute 'DSSKey'

Previous version never prompts for **paramiko** module. What has changes to prevent me from connecting to any registered database?

I even created a new server (from one of my server), and got the same message. Why is that?

Appreciated your help.

Eddy Soeparmin

**Comment by robe2** [comment]
I have the same issue too on Windows 11 using pgAdmin 9.7, but pgAdmin 9.6 works okay.

**Comment by akshay-joshi** [comment]
As mentioned in the ticket 9090, we’ve pinned Paramiko to version 3.5.1. Could someone please test the nightly build and let us know if the issue is resolved? [Nightly Build](https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2025-08-26/)

**Comment by robe2** [comment]
confirm works for me on windows 11
