### ISSUE TITLE
Fix to work with psycopg2 2.8 (RM #4143)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#2497]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/4143***
*Originally created by **Dave Page** at 2019-04-05 08:17:46 UTC.*

[2019-04-04 16:10:10 +0000] [5850] [INFO] Starting gunicorn 19.9.0
[2019-04-04 16:10:10 +0000] [5850] [INFO] Listening at:
unix:/home/ubuntu/pgadmin.sock (5850)
[2019-04-04 16:10:10 +0000] [5850] [INFO] Using worker: gthread
[2019-04-04 16:10:10 +0000] [5853] [INFO] Booting worker with pid: 5853
2019-04-04 16:10:25,732: ERROR  flask.app:
'psycopg2.extensions.Column' object has no attribute '_asdict'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line
1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line
1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.6/dist-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pgadmin4/pgadmin/browser/utils.py",
line 259, in dispatch_request
    return method(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pgadmin4/pgadmin/browser/utils.py",
line 309, in children
    children.extend(module.get_nodes(*args, **kwargs))
  File "/usr/local/lib/python3.6/dist-packages/pgadmin4/pgadmin/browser/server_groups/servers/__init__.py",
line 127, in get_nodes
    in_recovery, wal_paused = recovery_state(conn, manager.version)
  File "/usr/local/lib/python3.6/dist-packages/pgadmin4/pgadmin/browser/server_groups/servers/__init__.py",
line 52, in recovery_state
    status, result = connection.execute_dict(recovery_check_sql)
  File "/usr/local/lib/python3.6/dist-packages/pgadmin4/pgadmin/utils/driver/psycopg2/connection.py",
line 1202, in execute_dict
    desc.to_dict() for desc in cur.ordered_description()
  File "/usr/local/lib/python3.6/dist-packages/pgadmin4/pgadmin/utils/driver/psycopg2/connection.py",
line 1202, in <listcomp>
    desc.to_dict() for desc in cur.ordered_description()
  File "/usr/local/lib/python3.6/dist-packages/pgadmin4/pgadmin/utils/driver/psycopg2/cursor.py",
line 94, in to_dict
    ores = OrderedDict(self.orig_col._asdict())
AttributeError: 'psycopg2.extensions.Column' object has no attribute '_asdict'

**Comment by dpage** [comment]
Issue closed on Redmine.
