### ISSUE TITLE
Unable to download files from File Manager

### ISSUE THREAD

**Issue by MaartenUreel** [pgadmin-org/pgadmin4#5368]
Since we upgraded to 6.14, we cannot download files from File Manager (backups etc) anymore.

In the network tab, we see a POST request upon trying to dowload the file, and the server returning:
```
{"success":0,"errormsg":"Filemanager.download() got an unexpected keyword argument 'req'","info":"","result":null,"data":null}
```

I tried different browsers, computers and even another instance (updated it to 6.14 and had the same issue).

**Comment by adityatoshniwal** [comment]
Looks like https://github.com/pgadmin-org/pgadmin4/commit/d967d5046dd3e334d6694c627aac068bed1108c9 this is the cause. @nikhil-mohite Can you please check this ?

**Comment by FaharAbbasRizvi** [comment]
This is resolved in the latest snapshot build
https://www.postgresql.org/ftp/pgadmin/pgadmin4/snapshots/2022-09-27

**Comment by IVTore** [comment]
Hi @FaharAbbasRizvi,
Unfortunately I discovered that there is no seperate containerized nightly snapshot and latest versions of pgadmin4 on docker hub. I still get "Filemanager.download() got an unexpected keyword argument 'req'" on dockerized server.
Any chance for us to obtain a dockerized server of fixed version?
Thanks in advance.

**Comment by dpage** [comment]
Nightly snapshots are published to Docker Hub, the last one ~9 hours ago:

`docker pull dpage/pgadmin4:snapshot`

**Comment by IVTore** [comment]
@dpage 
Sorry my bad...
Thank you.
I will try that by editing my compose file now. 
 
FYI:
There is no indication for whereabouts of snapshot in the documentation @
https://www.pgadmin.org/docs/pgadmin4/development/container_deployment.html
which is addressed @
https://hub.docker.com/r/dpage/pgadmin4/

**Comment by dpage** [comment]
No problem :-). I've pushed a doc update that explains the available tags in commit [8875d8b](https://github.com/dpage/pgadmin4/commit/8875d8b74172390fb264cf6323a4663b3f1d0947).
