### ISSUE TITLE
pgAdmin4 4.18 not working after apdating Werkzeug to 1.0.0 (uWSGI) (RM #5209)

### ISSUE THREAD

**Issue by dpage** [pgadmin-org/pgadmin4#3333]
***Issue migrated from Redmine: https://redmine.postgresql.org/issues/5209***
*Originally created by **Rustam S.** at 2020-02-21 19:11:25 UTC.*

Python 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0] on linux (Ubuntu Server 18.04 LTS 4.15.0-88-generic)

pgadmin4==4.18
 - Werkzeug *[required: >=0.15.0, installed: 1.0.0]*

mounting pgAdmin4:app on /pgadmin4
Traceback (most recent call last):
  File "./pgAdmin4.py", line 40, in <module>
    import config
  File "/srv/mysrv/www/pgadmin4/venv_py36/lib/python3.6/site-packages/pgadmin4/config.py", line 30, in <module>
    from pgadmin.utils import env, IS_PY2, IS_WIN, fs_short_path
  File "/srv/mysrv/www/pgadmin4/venv_py36/lib/python3.6/site-packages/pgadmin4/pgadmin/__init__.py", line 25, in <module>
    from flask_security import Security, SQLAlchemyUserDatastore, current_user
  File "/srv/mysrv/www/pgadmin4/venv_py36/lib/python3.6/site-packages/flask_security/__init__.py", line 13, in <module>
    from .core import Security, RoleMixin, UserMixin, AnonymousUser, current_user
  File "/srv/mysrv/www/pgadmin4/venv_py36/lib/python3.6/site-packages/flask_security/core.py", line 28, in <module>
    from .forms import ChangePasswordForm, ConfirmRegisterForm, \
  File "/srv/mysrv/www/pgadmin4/venv_py36/lib/python3.6/site-packages/flask_security/forms.py", line 17, in <module>
    from flask_wtf import FlaskForm as BaseForm
  File "/srv/mysrv/www/pgadmin4/venv_py36/lib/python3.6/site-packages/flask_wtf/__init__.py", line 17, in <module>
    from .recaptcha import *
  File "/srv/mysrv/www/pgadmin4/venv_py36/lib/python3.6/site-packages/flask_wtf/recaptcha/__init__.py", line 2, in <module>
    from .fields import *
  File "/srv/mysrv/www/pgadmin4/venv_py36/lib/python3.6/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/srv/mysrv/www/pgadmin4/venv_py36/lib/python3.6/site-packages/flask_wtf/recaptcha/widgets.py", line 5, in <module>
    from werkzeug import url_encode
ImportError: cannot import name 'url_encode'
unable to load app 0 (mountpoint='/pgadmin4') (callable not found or import error)

Working on Werkzeug 0.16.1
