### ISSUE TITLE
servers.json file no longer loading at startup

### ISSUE THREAD

**Issue by andrewcottam** [pgadmin-org/pgadmin4#5776]
In version 6.18 you could automatically load server definitions from a file but this is no longer working in 6.19. Looking at the server logs for 6.18 we see:
```
Added 0 Server Group(s) and 1 Server(s).
```
But in 6.19:
```
'AnonymousUser' object has no attribute 'username'
```

**Comment by yogeshmahajan-1903** [comment]
This duplicate of https://github.com/pgadmin-org/pgadmin4/issues/5751 . Fix will be available in 6.20 release.
Currently you use daily snapshot build to verify.
Alternatively, you can import/export servers options from UI. Tools > Import/Export Servers.
