### ISSUE TITLE
setup.py user-management commands crash with AttributeError: 'PgAdmin' object has no attribute 'login_manager' in v9.14+

### ISSUE THREAD

**Issue by andrewlecuyer** [pgadmin-org/pgadmin4#9987]
**Describe the bug**

Running `setup.py` user management utilities (such as `update-user` or `add-user`) via the command line throws a fatal runtime exception. This structurally blocks configuration automation frameworks, configuration scripts, and Kubernetes operators from handling out-of-band administrative user changes or automated password rotations.

**To Reproduce**

1. Install pgAdmin4 v9.15 (or v9.14).
2. Execute the standard documented user update command from a terminal context: 
```bash
python3 /usr/local/lib/python3.11/site-packages/pgadmin4/setup.py update-user rhino@example.com --password abc123 --role Administrator
```
3. See the error:
```bash
$ python3 /usr/local/lib/python3.11/site-packages/pgadmin4/setup.py update-user rhino@example.com --password abc123 --role Administrator
╭────────────────────────────────────────────────────────────────────────────────────── Traceback (most recent call last) ───────────────────────────────────────────────────────────────────────────────────────╮
│ /usr/local/lib/python3.11/site-packages/pgadmin4/setup.py:73 in wrap                                                                                                                                           │
│                                                                                                                                                                                                                │
│    70 │   │   if kwargs and kwargs.get('sqlite_path') is not None:                                                                                                                                             │
│    71 │   │   │   # update the sqlite path                                                                                                                                                                     │
│    72 │   │   │   config.SQLITE_PATH = kwargs['sqlite_path']                                                                                                                                                   │
│ ❱  73 │   │   return f(*args, **kwargs)                                                                                                                                                                        │
│    74 │                                                                                                                                                                                                        │
│    75 │   return wrap                                                                                                                                                                                          │
│    76                                                                                                                                                                                                          │
│                                                                                                                                                                                                                │
│ /usr/local/lib/python3.11/site-packages/pgadmin4/setup.py:432 in update_user                                                                                                                                   │
│                                                                                                                                                                                                                │
│   429 │   │                                                                                                                                                                                                    │
│   430 │   │   app = create_app(config.APP_NAME + '-cli')                                                                                                                                                       │
│   431 │   │   with app.test_request_context():                                                                                                                                                                 │
│ ❱ 432 │   │   │   rid = ManageRoles.get_role(data['role'])                                                                                                                                                     │
│   433 │   │   │   if rid is None:                                                                                                                                                                              │
│   434 │   │   │   │   print("Role '{0}' does not exists.".format(data['role']))                                                                                                                                │
│   435 │   │   │   │   exit()                                                                                                                                                                                   │
│                                                                                                                                                                                                                │
│ /usr/local/lib/python3.11/site-packages/pgadmin4/setup.py:154 in get_role                                                                                                                                      │
│                                                                                                                                                                                                                │
│   151 class ManageRoles:                                                                                                                                                                                       │
│   152 │   @staticmethod                                                                                                                                                                                        │
│   153 │   def get_role(role: str):                                                                                                                                                                             │
│ ❱ 154 │   │   app = create_app(config.APP_NAME + '-cli')                                                                                                                                                       │
│   155 │   │   usr = None                                                                                                                                                                                       │
│   156 │   │   with app.test_request_context():                                                                                                                                                                 │
│   157 │   │   │   usr = Role.query.filter_by(name=role).first()                                                                                                                                                │
│                                                                                                                                                                                                                │
│ /usr/local/lib/python3.11/site-packages/pgadmin4/pgadmin/__init__.py:498 in create_app                                                                                                                         │
│                                                                                                                                                                                                                │
│   495 │   │   │   run_migration_for_sqlite()                                                                                                                                                                   │
│   496 │   │                                                                                                                                                                                                    │
│   497 │   │   # Delete all the adhoc(temporary) servers from the pgAdmin database.                                                                                                                             │
│ ❱ 498 │   │   delete_adhoc_servers()                                                                                                                                                                           │
│   499 │                                                                                                                                                                                                        │
│   500 │   Mail(app)                                                                                                                                                                                            │
│   501                                                                                                                                                                                                          │
│                                                                                                                                                                                                                │
│ /usr/local/lib/python3.11/site-packages/pgadmin4/pgadmin/browser/server_groups/servers/utils.py:692 in delete_adhoc_servers                                                                                    │
│                                                                                                                                                                                                                │
│   689 │   during app startup (no user context), cleans all adhoc servers.                                                                                                                                      │
│   690 │   """                                                                                                                                                                                                  │
│   691 │   try:                                                                                                                                                                                                 │
│ ❱ 692 │   │   has_user = (has_request_context() and                                                                                                                                                            │
│   693 │   │   │   │   │   current_user and current_user.is_authenticated)                                                                                                                                      │
│   694 │   │   if sid is not None:                                                                                                                                                                              │
│   695 │   │   │   q = db.session.query(Server).filter(                                                                                                                                                         │
│                                                                                                                                                                                                                │
│ /usr/local/lib/python3.11/site-packages/werkzeug/local.py:318 in __get__                                                                                                                                       │
│                                                                                                                                                                                                                │
│   315 │   │   │   return self                                                                                                                                                                                  │
│   316 │   │                                                                                                                                                                                                    │
│   317 │   │   try:                                                                                                                                                                                             │
│ ❱ 318 │   │   │   obj = instance._get_current_object()                                                                                                                                                         │
│   319 │   │   except RuntimeError:                                                                                                                                                                             │
│   320 │   │   │   if self.fallback is None:                                                                                                                                                                    │
│   321 │   │   │   │   raise                                                                                                                                                                                    │
│                                                                                                                                                                                                                │
│ /usr/local/lib/python3.11/site-packages/werkzeug/local.py:526 in _get_current_object                                                                                                                           │
│                                                                                                                                                                                                                │
│   523 │   │   elif callable(local):                                                                                                                                                                            │
│   524 │   │   │                                                                                                                                                                                                │
│   525 │   │   │   def _get_current_object() -> T:                                                                                                                                                              │
│ ❱ 526 │   │   │   │   return get_name(local())                                                                                                                                                                 │
│   527 │   │                                                                                                                                                                                                    │
│   528 │   │   else:                                                                                                                                                                                            │
│   529 │   │   │   raise TypeError(f"Don't know how to proxy '{type(local)}'.")                                                                                                                                 │
│                                                                                                                                                                                                                │
│ /usr/local/lib/python3.11/site-packages/flask_login/utils.py:25 in <lambda>                                                                                                                                    │
│                                                                                                                                                                                                                │
│    22                                                                                                                                                                                                          │
│    23 #: A proxy for the current user. If no user is logged in, this will be an                                                                                                                                │
│    24 #: anonymous user                                                                                                                                                                                        │
│ ❱  25 current_user = LocalProxy(lambda: _get_user())                                                                                                                                                           │
│    26                                                                                                                                                                                                          │
│    27                                                                                                                                                                                                          │
│    28 def encode_cookie(payload, key=None):                                                                                                                                                                    │
│                                                                                                                                                                                                                │
│ /usr/local/lib/python3.11/site-packages/flask_login/utils.py:370 in _get_user                                                                                                                                  │
│                                                                                                                                                                                                                │
│   367 def _get_user():                                                                                                                                                                                         │
│   368 │   if has_request_context():                                                                                                                                                                            │
│   369 │   │   if "_login_user" not in g:                                                                                                                                                                       │
│ ❱ 370 │   │   │   current_app.login_manager._load_user()                                                                                                                                                       │
│   371 │   │                                                                                                                                                                                                    │
│   372 │   │   return g._login_user                                                                                                                                                                             │
│   373                                                                                                                                                                                                          │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
AttributeError: 'PgAdmin' object has no attribute 'login_manager'
```

**Expected behavior**

In v9.13, the command completes without any errors:

```bash
$ python3 /usr/local/lib/python3.11/site-packages/pgadmin4/setup.py update-user rhino@example.com --password abc123 --role Administrator
           User Details
+---------------------------------+
| Field       | Value             |
|-------------+-------------------|
| Username    | rhino@example.com |
| Email       | rhino@example.com |
| auth_source | internal          |
| role        | Administrator     |
| active      | True              |
+---------------------------------+
```

**Error message**

```
AttributeError: 'PgAdmin' object has no attribute 'login_manager'
```

**Screenshots**

N/A

**Desktop (please complete the following information):**
 - OS: Linux (UBI9)
 - pgAdmin version: 9.15
 - Mode: Server
 - Browser (if running in server mode): N/A
 - Package type: Python

**Additional context**

N/A

**Comment by asheshv** [comment]
Thanks for the detailed traceback — diagnosed and fixed in draft PR #10008.

**Root cause:** This is a regression from PR #9830 ("enforce data isolation and harden shared servers in server mode"), which added a per-user scoping check to `delete_adhoc_servers()` that touches `current_user.is_authenticated`.

The call sequence on the CLI path:

1. `setup.py update-user` wraps its work in `app.test_request_context()` (needed so SQLAlchemy sessions work).
2. → `create_app('...-cli')` is invoked.
3. → `pgadmin/__init__.py:498` calls `delete_adhoc_servers()`.
4. → That reads `current_user.is_authenticated`.
5. → Flask-Login's proxy calls `current_app.login_manager._load_user()`.
6. → **`login_manager` is installed at `create_app:546` (Flask-Security `init_app`), AFTER the line-498 call** — hence `AttributeError: 'PgAdmin' object has no attribute 'login_manager'`.

In normal **web startup** the same code path runs, but `has_request_context()` returns `False` there, so the guard short-circuits before touching `current_user`. CLI is different because `setup.py` deliberately opens a test request context.

**Fix shape:** wrap the cleanup call at `pgadmin/__init__.py:498` in `if not cli_mode:` — adhoc servers are a UI/tool concept (Schema Diff workspaces, Query Tool ad-hoc connections, etc.). They have no meaning in a CLI session that only updates one user row.

**Workaround until the fix lands:**

Pin to v9.13 if you can. Otherwise apply this minimal patch locally to `<install-prefix>/pgadmin4/pgadmin/__init__.py` around line 498:

```diff
-        # Delete all the adhoc(temporary) servers from the pgAdmin database.
-        delete_adhoc_servers()
+        # Adhoc servers are a UI/tool concept; they have no meaning in
+        # CLI sessions, and the per-user scoping check would crash
+        # because Flask-Security has not yet been initialised here.
+        if not cli_mode:
+            delete_adhoc_servers()
```

That removes the CLI crash without affecting web/server mode startup cleanup.

**Comment by dpage** [comment]
This was fixed and is included in **pgAdmin 4 9.16** (via PR #10008). The fix is listed in the 9.16 release notes; the auto-close keyword on the merged PR didn't fire, so closing manually. Please reopen if you still see it on 9.16+.
