### ISSUE TITLE
Loading of server definition using servers.json failed in v6.19, but works in v6.18

### ISSUE THREAD

**Issue by brianktp** [pgadmin-org/pgadmin4#5814]
**Describe the bug**
When running a docker container using latest release v6.19, with input of servers.json file containing a server definition, the server config doesn't appear in the Server group upon login into web client. But when revert back to image v6.19, it's works.

**To Reproduce**
1. docker pull dpage/pgadmin4
2. Setup the servers.json with a server definition. e.g.
_{
  "Servers": {
    "1": {
        "Name": "Ops",
        "Group": "Servers",
        "Host": "host",
        "Port": 5432,
        "MaintenanceDB": "postgres",
        "Username": "devops",
        "SSLMode": "prefer",
        "Shared": true,
        "SSLCert": "<STORAGE_DIR>/.postgresql/postgresql.crt",
        "SSLKey": "<STORAGE_DIR>/.postgresql/postgresql.key",
        "SSLCompression": 0,
        "Timeout": 10,
        "UseSSHTunnel": 0,
        "TunnelPort": "22",
        "TunnelAuthentication": 0
    }
  }
}_

3. docker run -p 80:80 \
    -e 'PGADMIN_DEFAULT_EMAIL=user@domain.com' \
    -e 'PGADMIN_DEFAULT_PASSWORD=SuperSecret' \
    -e 'PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION=True' \
    -e 'PGADMIN_CONFIG_CONSOLE_LOG_LEVEL=10' \
    -v /tmp/servers.json:/pgadmin4/servers.json \
    -d dpage/pgadmin4

5. From the docker container logs, observe following message:

        Loading servers with:
        User: user@domain.com
        SQLite pgAdmin config: /var/lib/pgadmin/pgadmin4.db
        
        'AnonymousUser' object has no attribute 'username'

6. Login into pgAdmin client as administrator, (http://localhost:80), observe that the server config is not appeared in the Servers group.

7. When Re-execute step 1 and 3 with docker image of v6.18(dpage/pgadmin4:6.18), and it works per expected. 

        Loading servers with:
        User: user@domain.com
        SQLite pgAdmin config: /var/lib/pgadmin/pgadmin4.db
        
        Added 0 Server Group(s) and 1 Server(s).

From the web client, observe the server config is loaded into Servers group.

**Expected behavior**

The server config per servers.json shall be loaded into Servers group upon login. 

**Error message**

Loading servers with:
User: user@domain.com
SQLite pgAdmin config: /var/lib/pgadmin/pgadmin4.db

**'AnonymousUser' object has no attribute 'username'**

**Screenshots**

NA.

**Additional context**

**Comment by adityatoshniwal** [comment]
Duplicates #5751. Fix will be available in 6.20 release planned next week.
Meanwhile, you use daily snapshot build to verify. You can also import/export servers options from UI. Tools > Import/Export Servers.

**Comment by brianktp** [comment]
Thank you @adityatoshniwal.
