### ISSUE TITLE
Cannot connect with SSH tunnel after upgrading to 9.7

### ISSUE THREAD

**Issue by gesmmg** [pgadmin-org/pgadmin4#9111]
After upgrading to version 9.7, I can no longer connect to remote servers using the SSH tunnel option. The "Connect to Server" dialog reopens asking to enter the password to unlock the SSH key and the password to connect to the server, but after entering the correct passwords it just reopens asking for both passwords again. An error message at the bottom of the dialog reads "module 'paramiko' has no attribute 'DSSKey'".

We use SSH keys for authentication. I am on Ubuntu 22.04.5 LTS.

I downgraded to version 9.6 and can connect without issues.
